### ISSUE TITLE
[BUG] Error: fromUuidSync was invoked on UUI

### ISSUE THREAD

**Issue by CaosFR** [p4535992/foundryvtt-rarity-colors#20]
Hi, 

I have a bug with rarity-color . It's dont work with sheet inside a compendium (system or user). 
It's working if you export your sheet to your game or if I use a item compendium.

**Describe the bug**

**To Reproduce**
1. Go to 'a sheet compendium'
2. Open a sheet
3. Open any action to edit
```
Error: fromUuidSync was invoked on UUID 'Compendium.mon-compendium-partager.monstres-partager.Actor.WrDj95t16BTLQUGT.Item.vowp2kgd28v1VwqG' which references an Embedded Document and cannot be retrieved synchronously.
    at fromUuidSync (foundry.js:4896:11)
    at RetrieveHelpers.stringIsUuid (retrieve-helpers.js:75:22)
    at RetrieveHelpers.getItemSync (retrieve-helpers.js:635:29)
    at Object.getColorFromItem (API.js:26:32)
    at renderItemSheetRarityColors (raritycolors.js:364:23)
    at Object.fn (raritycolors.js:199:5)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ItemSheet5e._render (foundry.js:5855:13)
    at async ItemSheet5e._render (foundry.js:6532:5)
```

**Screenshots**
Sheet compendium NOK
![image](https://github.com/user-attachments/assets/43b7733e-0185-4835-9f9c-7af8c12a2373)

Item compendium OK
![image](https://github.com/user-attachments/assets/8c0ad473-86f3-4d8b-be18-bd8df8f1c247)

Sheet exported from compendium OK
![image](https://github.com/user-attachments/assets/15b85739-149a-4804-856a-6fae6590be02)

**Browser:**
Chromium Version 126.

**Foundry Version:** 
Foundry v11.315

**Game System:** 
Dnd 3.3.1

**Additional context**

Reset settings to default or disable Rarity Color in compendium dont resolve the bug.

**Comment by CaosFR** [comment]
Any news ?

**Comment by p4535992** [comment]
Sorry for the delay my free time is very short recently , i really hope after summer to come back to this
